---
#this playbook is for k8s work nodes.

- name: Copy install script to k8s node
  copy:
    src: kubeadm_install_node.sh
    dest: /tmp/kubeadm_install_node.sh
    mode: "0755"
  tags: k8s_node

- name: Node Join to k8s cluster
  shell: /tmp/kubeadm_install_node.sh
  tags: k8s_node
